# Generated by Django 5.1.1 on 2024-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_alter_menuitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url_path',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
