# Generated by Django 5.1.1 on 2024-09-19 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_menuitem_url_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url_path',
        ),
    ]
